<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-J6V7M0GL" failures="1" tests="3" name="Sign Up Test" time="0.073" errors="0" timestamp="2024-11-27T20:57:16 IST">
  <testcase classname="TestNGPackage.signUpTest" name="signUpTestCase1" time="0.008">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TestNGPackage.signUpTest.signUpTestCase1(signUpTest.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- signUpTestCase1 -->
  <testcase classname="TestNGPackage.signUpTest" name="signUpTestCase2" time="0.007"/>
  <testcase classname="TestNGPackage.signUpTest" name="signUpTestCase3" time="0.005"/>
</testsuite> <!-- Sign Up Test -->
